### ISSUE TITLE
Dedicated server

### ISSUE THREAD

**Issue by BlackHawk94** [doctorluk/rotu-revolution#7]
Hello, i have an error after start the server with the latest B3 and ROTU-R

compile script: error token '"'
Linux Build 1.7a
Linux Build 1.8

the mod work good without scripts folder

**Comment by doctorluk** [comment]
Hi there.

Which version of RotU-R are you running?

**Comment by BlackHawk94** [comment]
2.2.2

**Comment by doctorluk** [comment]
I'm sorry, but there is no version 2.2.2 of RotU-R.

Are you sure you're using our mod?

You can find our mod's public releases at https://rotu-revolution.com/download.php

**Comment by BlackHawk94** [comment]
yeah, sorry i build the mod from this source and used alpha 0.7 too, still the same error building script and server doesnt start.

**Comment by BlackHawk94** [comment]
Thanks for your time, i fixed the error.

the server dont read sv_maprotation_1 in maps.cfg
so i had to add it on general.cfg

**Comment by BlackHawk94** [comment]
Server online + B3 + Rotu stats enabled and now commands not work, you know why?

**Comment by AlexanderCurl** [comment]
Disable xlrstats in b3.

**Comment by BlackHawk94** [comment]
thanks, all work now.
only fps and fov are still unable to work

**Comment by AlexanderCurl** [comment]
In rotu mod doesn't have fps and fov command.

**Comment by BlackHawk94** [comment]
but B3 does

**Comment by BlackHawk94** [comment]
But b3 has these commands, maybe you mean that they are not added in the source code?

**Comment by doctorluk** [comment]
Do the commands "fps" and "fov" change a player's FPS and FOV?

If so, there is no such command implemented into RotU-R. For this to work, the mod has to add those commands to be usable by external programs such as B3.

**Comment by AlexanderCurl** [comment]
B3 doesn't have these commands either, you have to use customcommands plugin to get it work, and as well the mod has to support also. But in RotU-R mod doesn't have any kind of code as @doctorluk said before.
